language: ruby
rvm:
- 2.4.2

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
- sudo apt-get update -qq
- sudo apt-get install --reinstall ca-certificates -y

notifications:
  email: false
