# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
permalink: /:title
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: UA-28304401-3
title: Federico Ariel Castagnini's blog
url: "http://blog.191161.xyz"

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
      title: Federico Castagnini's blog

description: Stylish Jekyll Theme
author:
  name: Federico Ariel Castagnini
  # email: federico.castagnini+fromjekyll@gmail.com
  github: facastagnini
  gitlab: facastagnini
  # twitter: dbtek
  # pinterest: asd123
  linkedin: fcastagnini
  hackerrank: facastagnini
  bio: A minimal blog about technology.
  # used to grab the gravatar
  email_md5: 074d48adc68e8fd2c71fa9d0d50de276

# rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
livereload: true

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
